#!/bin/bash
# author: yin-jianhong@163.com
# version: v0.99
# dependency: iproute2 tmux
# used to create netns and add ifs into it

LANG=C
P=$0
[[ $0 = /* ]] && P=${0##*/}
AT=("$@")

switchroot() {
	[[ $(id -u) != 0 ]] && {
		echo -e "{NETNS:WARN} $P need root permission, switch to:\n  sudo $P ${AT[@]}" | GREP_COLORS='ms=1;30' grep --color=always . >&2
		exec sudo $P "${AT[@]}"
	}
}

Usage() {
	cat <<-EOF
	Usage:
	  $P <\$nsname,\$vethX,\$addr---\$nsname,\$vethX_peer,\$addr | \$nsname,\$vnic_name[,\$addr][?updev=\$if,mode=\$mode,type=\$type]>
	  # ^^^^^^ nsname 'host' means default network namespace
	  $P exec \$nsname -- cmdline
	  $P del \$nsname
	  $P ls

	  $P veth ve0.a-host,ve0.b-ns0   #create veth pair
	  $P macvlan ifname              #create macvlan if; [updev=updev] [mode={bridge|vepa|private|passthru}]
	  $P ipvlan ifname               #create ipvlan if; [updev=updev] [mode={l2|l3}]

	  $P addrup \$if \$address         #set address and up if
	  $P attach \$ns \$if [\$addr]      #attach new if to ns, [and setup address and up]
	  $P detach \$ns \$if              #detach if from ns

	Options:
	  -h, --help           ; show this help info
	  -v                   ; verbose mode
	  -n <arg>             ; ns name

	Examples:
	  $P host,ve0.a-host,192.168.0.1---ns0,ve0.b-ns0,192.168.0.2   host,iv-host0,192.168.99.1?type=ipvlan ns0,iv-ns0,192.168.99.2?type=ipvlan
	  $P del ns0
	  $P delif iv-host0

	  $P host,ve0.a-host,192.168.0.1---ns0,ve0.b-ns0,192.168.0.2  host,mv-host0,192.168.100.1 ns0,mv-ns0,192.168.100.2
	  # ^^^^^^ nsname 'host' means default network namespace
	  $P -v exec ns0 -- ping -c 2 192.168.0.1
	  $P -v exec ns0 -- ping -c 2 192.168.100.1
	  #curl -s -L https://raw.githubusercontent.com/tcler/linux-network-filesystems/master/tools/configure-nfs-server.sh | sudo bash
	  sudo systemctl start nfs-server
	  sudo exportfs -o ro,no_root_squash "*:/usr/share"
	  $P -v exec ns0 -- showmount -e 192.168.0.1
	  $P -v exec ns0 -- mkdir -p /mnt/ns0/nfs
	  $P -v exec ns0 -- mount 192.168.0.1:/ /mnt/ns0/nfs
	  $P -v exec ns0 -- mount -t nfs4
	  $P -v exec ns0 -- ls /mnt/ns0/nfs/*
	  $P -v exec ns0 -- umount /mnt/ns0/nfs
	  $P -v exec ns0 -- rm -rf /mnt/ns0
	  $P del ns0
	  sudo ip link delete dev mv-host0

	EOF
}

is_valid_ip() {
    local  ip=$1
    local  stat=1

    ip=${ip%/*}
    if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        ip=(${ip//./ })
        [[ ${ip[0]} -le 255 && ${ip[1]} -le 255 \
            && ${ip[2]} -le 255 && ${ip[3]} -le 255 ]]
        stat=$?
    fi
    return $stat
}

ns_init_pid() {
	local ns=$1
	local initpid

	initpid=$(tmux list-panes -a -F '#{session_name} #{pane_pid}' | awk -v ns="$ns" '$1 == ns {print $2}')
	[[ -z "$initpid" ]] && return 1
	echo $initpid
}

_nsexec() {
	local initpid=$1
	shift
	nsenter --target "$initpid" --mount --uts --ipc --net --pid -- bash -c "$*"
}

nsexec() {
	local ns=$1
	shift
	local initpid=$(ns_init_pid $ns)
	[[ "$nsverbose" = yes ]] && echo "- [NETNS:$ns] # $@" | GREP_COLORS='ms=01;36' grep --color . >&2
	_nsexec "$initpid" "$@"
}

nsdelete() {
	for ns; do
		echo -e "\n{NETNS:INFO} remove ns $ns ..."

		echo -e "- {NETNS:INFO} remove ifs in ns ..."
		for dev in $(nsexec $ns ip a s | awk -F'[: @]+' '/^[0-9]+:/ {if ($2 != "lo") print $2}'); do
			nsexec $ns ip link del "$dev"
		done
		nsexec $ns ip a s

		echo -e "- {NETNS:INFO} exit init bash ..."
		tmux send-keys -t "$ns" C-z " exit; exit" Enter

		echo -e "- {NETNS:INFO} remove netns ..."
		ip netns del $ns 2>/dev/null
	done
}


attachif () {
	local ns=$1
	local if=$2
	local addr=$3

	xaddr() {
		local addr=$1
		[[ "$addr" =~ .*/[1-9]+$ ]] || addr+=/24
		echo $addr
	}

	ip link set $if netns $ns
	nsexec $ns ip link set dev $if up

	[[ -n "$addr" ]] && nsexec $ns ip addr add $(xaddr $addr) dev $if
}

detachif () {
	local ns=$1
	local if=$2
	ip netns exec $ns ip link set $if netns 1
}

addveth() {
	local fname=${FUNCNAME[0]}
	Usage() { echo -e "Usage:\n  $fname vename.x,vename.y [vename2.x,vename2.y ...]"; }

	if [[ "${#}" = 0 ]]; then
		Usage >&2
		return 1
	fi

	for pair; do
		read end0 end1 _ <<<"${pair//,/ }"
		if [[ -n "$end0" && -n "$end1" ]]; then
			ip link add $end0 type veth peer name $end1
		else
			Usage >&2
		fi
	done
}
addmacvlan() {
	local fname=${FUNCNAME[0]}
	Usage() { echo -e "Usage:\n  $fname [-updev=updev] [-mode={bridge|vepa|private|passthru}] mv1 [mv2 ...]"; }
	get_default_if() { ip route | awk '/default/{match($0,"dev ([^ ]+)",M); print M[1]; exit}'; }

	local updev=$(get_default_if)
	local mode=bridge

	# parse options
	local mvs=()
	for arg; do
		case "$arg" in
		updev=*|-updev=*) val=${arg#*=}; [[ -n "$val" ]] && updev="$val";;
		mode=*|-mode=*)  val=${arg#*=}; [[ -n "$val" ]] && mode="$val";;
		-*)       echo "{WARN} unkown option '${arg}'" >&2;;
		*)        mvs+=($arg);;
		esac
	done

	if [[ "${#mvs[@]}" = 0 ]]; then
		Usage >&2
		return 1
	fi

	for mv in $mvs; do
		ip link add link $updev name ${mv} type macvlan mode $mode
	done
}
addipvlan() {
	local fname=${FUNCNAME[0]}
	Usage() { echo -e "Usage:\n  $fname [-updev=updev] [-mode={l2|l3}] iv1 [iv2 ...]"; }
	get_default_if() { ip route | awk '/default/{match($0,"dev ([^ ]+)",M); print M[1]; exit}'; }

	local updev=$(get_default_if)
	local mode=l2

	# parse options
	local ivs=()
	for arg; do
		case "$arg" in
		updev=*|-updev=*) val=${arg#*=}; [[ -n "$val" ]] && updev="$val";;
		mode=*|-mode=*)  val=${arg#*=}; [[ -n "$val" ]] && mode="$val";;
		-*)       echo "{WARN} unkown option '${arg}'" >&2;;
		*)        ivs+=($arg);;
		esac
	done

	if [[ "${#ivs[@]}" = 0 ]]; then
		Usage >&2
		return 1
	fi

	for iv in $ivs; do
		ip link add link $updev name ${iv} type ipvlan mode $mode
	done
}
addressup() {
	local if=$1
	local addr=$2

	xaddr() {
		local addr=$1
		[[ "$addr" =~ .*/[1-9]+$ ]] || addr+=/24
		echo $addr
	}

	ip link set dev $if up
	ip addr add $(xaddr $addr) dev $if
}
delif() {
	for if; do
		ip link delete dev $if
	done
}

# command line parse
_at=`getopt -o hvn: \
	--long help \
    -a -n "$0" -- "$@"`
eval set -- "$_at"
while true; do
	case "$1" in
	-h|--help) Usage; shift 1; exit 0;;
	-n) NS="$2"; shift 2;;
	-v) nsverbose=yes; shift 1;;
	--) shift; break;;
	esac
done

switchroot
# __prepare__
which tmux &>/dev/null || dep+=\ tmux
[[ -n "$dep" ]] && {
	echo -e "{NS:INFO} install dependences ..."
	sudo yum install -y $dep >&2
}

# __main__
subcmd=$1
case $subcmd in
exec|exe|ex|e) shift
	[[ -z "$NS" ]] && { NS=$1; shift; }
	[[ -z "$NS" ]] && { Usage >&2; exit 1; }
	nsexec $NS "$@"
	exit $?;;
delif) shift
	delif "$@"
	exit $?;;
del*|de|d) shift
	[[ -z "$NS" ]] && { NS=$1; shift; }
	[[ -z "$NS" ]] && { Usage >&2; exit 1; }
	nsdelete $NS "$@"
	exit $?;;
ls) shift
	ip netns
	exit $?;;
veth|addveth) shift
	addveth "$@"
	exit $?;;
macvlan|addmacvlan) shift
	addmacvlan "$@"
	exit $?;;
ipvlan|addipvlan) shift
	addipvlan "$@"
	exit $?;;
addr|addrup|addressup) shift
	addressup "$@"
	exit $?;;
attach) shift
	[[ -z "$NS" ]] && { NS=$1; shift; }
	[[ -z "$NS" ]] && { Usage >&2; exit 1; }
	attachif "$@"
	exit $?;;
detach) shift
	[[ -z "$NS" ]] && { NS=$1; shift; }
	[[ -z "$NS" ]] && { Usage >&2; exit 1; }
	detachif "$@"
	exit $?;;
creat*) shift
	[[ -z "$NS" ]] && { NS=$1; shift; }
	;;
esac

[[ $# = 0 ]] && {
	Usage >&2
	exit 1
}

VethList=()
VNICList=()
declare -A NS_IFS
echo -e "\n{NETNS:INFO} parse parameters ..."
for topo; do
	# ns that connected to/by veth: host,veth0.x,192.168.0.1---ns0,veth0.y,192.168.0.2
	if [[ "$topo" =~ ^[^,]+,[^,]+,[^,]+---+[^,]+,[^,]+,[^,]+$ ]]; then
		topo=$(echo "$topo"|sed -r 's/---+/ /')
		read nodeX nodeY _ <<<"${topo}"
		read nsX vethX addrX _ <<<"${nodeX//,/ }"
		read nsY vethY addrY _ <<<"${nodeY//,/ }"
		VethList+=($vethX,$vethY)
		NS_IFS[$nsX]+=" $vethX,$addrX"
		NS_IFS[$nsY]+=" $vethY,$addrY"
	# ns that connected to macvlan
	elif [[ "$topo" =~ ^[^,]+,[^,]+(,[0-9.]+)?(\?((updev|mode|type)=.*)(,((updev|mode|type)=.*))*)?$ ]]; then
		read ifinfo env _ <<<"${topo/\?/ }"
		read ns ifname addr _ <<<"${ifinfo//,/ }"
		NS_IFS[$ns]+=" $ifname,$addr"
		VNICList+=($ifname,${env})
	else
		echo -e "{NETNS:ERR} invalid format '\E[1;31m$topo\E[0m', see Usage:"
		Usage >&2
		exit 1
	fi
done

# creating all NS
for NS in "${!NS_IFS[@]}"; do
	[[ "$NS" = host ]] && continue

	echo -e "{NETNS:INFO} creating NS $NS ..."
	ip netns add "$NS"
	tmux new -s "$NS" -d "ip netns exec \"$NS\" /bin/bash"
done

# creating all veth ifs
for veth in "${VethList[@]}"; do
	read vethX vethY _ <<<"${veth/,/ }"
	echo -e "{NETNS:INFO} creating veth pair $vethX $vethY ..."
	addveth $vethX,$vethY
done

# creating other VNICs
for vnicinfo in "${VNICList[@]}"; do
	type=
	updev=
	mode=

	read vif env <<<"${vnicinfo/,/ }"
	eval ${env//,/ }

	if [[ -z "$type" || "$type" = macvlan ]]; then
		echo -e "{NETNS:INFO} creating macvlan $vif ${env//,/ } ..."
		addmacvlan $vif -updev=$updev -mode=$mode
	elif [[ "$type" = ipvlan ]]; then
		echo -e "{NETNS:INFO} creating iplan $vif ${env//,/ } ..."
		addipvlan $vif -updev=$updev -mode=$mode
	else
		:
	fi
done

# attach ifs to NS
for NS in "${!NS_IFS[@]}"; do
	for IFLIST in ${NS_IFS[$NS]}; do
		read ifname addr _ <<<"${IFLIST/,/ }"
		echo -e "{NETNS:INFO} attach $ifname to ns($NS) and set ip address($addr) ..."
		if [[ "$NS" = host ]]; then
			addressup $ifname $addr
		else
			attachif "$NS" $ifname $addr
		fi
	done
done
