#!/bin/bash

sshOpts=${sshOpts:--oUserKnownHostsFile=/dev/null -oStrictHostKeyChecking=no -oGSSAPIAuthentication=no}
sshOpts+=" -oHostKeyAlgorithms=+ssh-rsa -oPubkeyAcceptedKeyTypes=+ssh-rsa"
sshOpts+=" -oKexAlgorithms=+diffie-hellman-group1-sha1,diffie-hellman-group1-sha1,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1"
/usr/bin/ssh $sshOpts "$@"
