#!ddif2bridge/bin/bash

addif2br-vrf-and-so-on() {
	local brname=$1
	local if=$2

	local fname=${FUNCNAME[0]}
	Usage() { echo -e "Usage:\n  $fname <net-dev-name> <ifname>"; }
	[[ $# -lt 2 ]] && {
		Usage >&2
		return 1
	}

	run ip link set dev $if master $brname
	run ip link set dev $if up
}
addif2br-vrf-and-so-on "$@"
