#!/bin/bash

run() {
	[[ $# -eq 0 ]] && return 0
	[[ "$DEBUG" != no ]] && echo "[sys]" "$@"
	"$@"
}

addif2br-vrf-and-so-on() {
	local netdevname=$1
	local if=$2

	local fname=${FUNCNAME[0]}
	Usage() { echo -e "Usage:\n  $fname <net-dev-name> <ifname>"; }
	[[ $# -lt 2 ]] && {
		Usage >&2
		return 1
	}

	run ip link set dev $if master $netdevname
	run ip link set dev $if up
}
addif2br-vrf-and-so-on "$@"

echo -e "{remind} the change we did will lost after reboot.\n{remind} please use nmcli or something else instead, if your want permanently." >&2
