#!/bin/bash

addmacvlan() {
	local fname=${FUNCNAME[0]}
	Usage() { echo -e "Usage:\n  $fname [-updev=updev] [-mode={bridge|vepa|private|passthru}] mv1 [mv2 ...]"; }
	get_default_if() { ip route | awk '/default/{match($0,"dev ([^ ]+)",M); print M[1]; exit}'; }

	local updev=$(get_default_if)
	local mode=bridge

	# parse options
	local mvs=()
	for arg; do
		case "$arg" in
		-updev=*) val=${arg/*=}; [[ -n "$val" ]] && updev="$val";;
		-mode=*)  val=${arg/*=/}; [[ -n "$val" ]] && mode="$val";;
		-*)       echo "{WARN} unkown option '${arg}'" >&2;;
		*)        mvs+=($arg);;
		esac
	done

	if [[ "${#mvs[@]}" = 0 ]]; then
		Usage >&2
		return 1
	fi

	for mv in $mvs; do
		ip link add link $updev name ${mv} type macvlan mode $mode
	done
}
addmacvlan "$@"
